### ISSUE TITLE
Genotype or merge TIPs across samples?

### ISSUE THREAD

**Issue by YTLogos** [bergmanlab/mcclintock#65]
Hi @cbergman 
Thanks for developing such a great pipeline to detect TE insertions. I found that the pipeline can just detect TIPs in one sample at a time. So after all samples are finished, is there any methods to genotype or merge all the TIPs across samples to a bed file to facilitate the next analysis?
Reagrds,
Tao

**Comment by cbergman** [comment]
Thanks for the suggestion @YTLogos. This is a good idea, but one that we don't current have plans to implement in the short term. One of the reasons why we haven't prioritized this is that the positional accuracy of different component methods differs, and can often be a relatively wide window. See Figs 2 and 3 from Nelson et al for some sense of how wide these windows can be. I'm tagging @shunhuahan on this, since he developed an ad hoc strategy to cluster non-reference predictions from different samples into orthologous loci using BEDtools. If Shunhua's approach is useful, we can think about adding this as an auxiliary script or process.

**Comment by YTLogos** [comment]
That's great! Looking forward to update！
