### ISSUE TITLE
Miss --make_annotations and --mem arguments

### ISSUE THREAD

**Issue by yanhaidong1** [bergmanlab/mcclintock#69]
Dear Bergman,

I am Haidong, a user of the mcclintock. I found this tool is more convenient to use than before. Thanks for the updating!
But I found there is no --make_annotations and --mem arguments in the current version. Or I go a wrong way to use it. Thanks!

Best wishes,
Haidong

**Comment by pbasting** [comment]
Hi Haidong,

You are right that the `--mem` argument has been removed, I'll update the readme to remove this from the usage. It was removed because, in previous versions, only a few steps had memory usage limited by the `--mem` option, while most of the pipeline would use memory unconstrained, so the `--mem` option gave the false impression that the entire pipeline was limited by the value provided to `--mem`.

The `--make_annotations` option is new to the most recent commit to master: https://github.com/bergmanlab/mcclintock/commit/3b6efab5f6eb10a432ba0818f561308a4cb3d22c . You may be using an older version of mcclintock if this option is not available. You can check the commit hash with:
```console
$ cd /path/to/mcclintock/
$ git rev-parse HEAD
3b6efab5f6eb10a432ba0818f561308a4cb3d22c
```
If your hash doesn't match the newest commit you will need to install the newest version of mcclintock to use the `--make_annotations` flag. If you are using the most recent version of mcclintock and the `--make_annotations` is still not working, please post an example of the command you are using so I can try and figure out what is going on.

Thanks,
Preston

**Comment by yanhaidong1** [comment]
Hi Preston,
Thanks! I will try the new version.
Best wishes,
Haidong
